services:
  aui-movie-management:
    image: aui-movie-management:0.0.1-SNAPSHOT
    restart: always

  aui-director-management:
    image: aui-director-management:0.0.1-SNAPSHOT
    restart: always
    environment:
      RPG_MOVIE_URL: "http://aui-movie-management:8080"

  aui-gateway-management:
    image:  aui-gateway-management:0.0.1-SNAPSHOT
    restart: always
    environment:
      RPG_MOVIE_URL: "http://aui-movie-management:8080"
      RPG_DIRECTOR_URL: "http://aui-director-management:8080"
      RPG_GATEWAY_HOST: "aui-gateway-management:8080"

  aui-js:
    image: aui-js:0.0.1-SNAPSHOT
    restart: always
    environment:
      API_URL: http://aui-gateway-management:8080/api
    ports:
      - "8086:80"

  aui-ng:
    image: aui-ng:0.0.1-SNAPSHOT
    restart: always
    environment:
      API_URL: http://aui-gateway-management:8080/api
    ports:
      - "8087:80"
